/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cheecks.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes._9.geometry} material={materials._09}>
        <mesh geometry={nodes._4.geometry} material={materials._09} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/cheecks.glb')
