/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/eyebrows.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.upward1.geometry} material={materials.aiStandardSurface3} />
      <mesh geometry={nodes.upward2.geometry} material={materials.aiStandardSurface3} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 1, -1]} />
    </group>
  )
}

useGLTF.preload('/eyebrows.glb')
