/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/eyes.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.L_eye.geometry} material={materials.lambert36} />
      <mesh geometry={nodes.R_eye.geometry} material={materials.lambert36} />
    </group>
  )
}

useGLTF.preload('/eyes.glb')
