/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/lower_cloth.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.lower_clothes_06_1.geometry} material={materials.aiStandardSurface6} />
      <mesh geometry={nodes.lower_clothes_06_2.geometry} material={materials.lambert37} />
    </group>
  )
}

useGLTF.preload('/lower_cloth.glb')
