/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/smile.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.smile_04.geometry} material={materials.lambert19} rotation={[-0.18, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/smile.glb')
