/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/upper_cloth.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.upper_clothes_09.geometry} material={materials.aiStandardSurface5} />
    </group>
  )
}

useGLTF.preload('/upper_cloth.glb')
